# Generated by Django 3.2.9 on 2023-05-31 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='kategori ismi')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='ülke ismi')),
            ],
        ),
        migrations.CreateModel(
            name='SihaIha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='İha-Siha isim')),
                ('brand', models.CharField(blank=True, max_length=40, null=True, verbose_name='Marka')),
                ('model', models.CharField(max_length=40, verbose_name='Model ismi')),
                ('weight', models.IntegerField(max_length=20, verbose_name='Ağırlık')),
                ('image', models.ImageField(upload_to='image')),
                ('description', models.CharField(blank=True, max_length=40, null=True, verbose_name='Ürün Açıklaması')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihaPage.category')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihaPage.country')),
            ],
        ),
    ]
