# Generated by Django 3.2.9 on 2023-05-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihaPage', '0002_auto_20230531_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sihaiha',
            name='category',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='İha-Siha isim'),
        ),
        migrations.AlterField(
            model_name='sihaiha',
            name='country',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='İha-Siha isim'),
        ),
    ]
